#
# /!\ WARNING /!\
# This docker-compose file should only be used for development environment
# using it for production is probably a bad idea
#
version: "3"

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    environment:
      PORT: 3000
